import Head from "next/head";
import Image from "next/image";
import styles from "../../../styles/Home.module.css";
import Pagination from "../../../components/Pagination";
import { paginate } from "./paginate";
import { useState } from "react";

export default function Home({ data }) {
    const [currentPage, setCurrentPage] = useState(1); // Deklarasikan state di sini
    const pageSize = 10; // Deklarasikan pageSize di sini

    const paginatedPosts = paginate(data, currentPage, pageSize); // Gunakan state setelah deklarasi

    const onPageChange = (page) => {
        setCurrentPage(page);
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <p>
                <strong>NextJS x Pagination</strong>
            </p>
            {paginatedPosts.map((item) => { // Gunakan paginatedPosts untuk menampilkan data yang dipaginasi
                return <p key={item.id}>{item.title}</p>;
            })}
            <Pagination
                items={data.length} // 100
                currentPage={currentPage} // 1
                pageSize={pageSize} // 10
                onPageChange={onPageChange}
            />
        </div>
    );
}

export const getStaticProps = async () => {
    const res = await fetch("https://jsonplaceholder.typicode.com/todos");
    const data = await res.json();

    return {
        props: { data },
    };
};
